spring.application.name=terraforming-mars
server.port=8081
server.ssl.enabled=false
server.servlet.context-path=/terraforming-mars
spring.datasource.url=jdbc:postgresql://${POSTGRESQL_HOSTNAME}:${POSTGRESQL_HOST_PORT}/terraforming-mars
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
