spring.application.name=terraforming-mars
server.port=8081
server.ssl.enabled=false
server.servlet.context-path=/terraforming-mars
spring.datasource.url=jdbc:h2:mem:clank;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;MODE=MYSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=clank
spring.datasource.password=clank
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.h2.console.enabled=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
