-- Debug seed data for the H2 in-memory database.
-- It is loaded only when the debug profile enables classpath:debug/data.sql.

CREATE SEQUENCE IF NOT EXISTS championship_seq START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS game_seq START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS player_seq START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS points_seq START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS drafting_seq START WITH 1000;

INSERT INTO player (id, nickname, fullname) VALUES
    (1, 'Capoz', 'Cristian Capozzi'),
    (2, 'Ludovick', 'Ludovica Rossi'),
    (3, 'Vanja', 'Ivan Marin'),
    (4, 'Gaia', 'Gaia Bianchi'),
    (5, 'Marco', 'Marco Verdi'),
    (6, 'Sofia', 'Sofia Conti'),
    (7, 'Luca', 'Luca Ferri'),
    (8, 'Elena', 'Elena Greco'),
    (9, 'Marta', 'Marta Moretti'),
    (10, 'Paolo', 'Paolo Ricci');

INSERT INTO championship (id, championship_name, starting_date, ending_date) VALUES
    (1, 'La casa di Terraforming Mars - Winter League', '2025-01-04 20:30:00', '2025-04-19 23:30:00'),
    (2, 'Tharsis Tuesday Championship', '2025-05-06 20:30:00', '2025-08-19 23:30:00'),
    (3, 'Hellas and Elysium Masters', '2025-09-05 20:30:00', '2025-12-12 23:30:00');

INSERT INTO game (id, location, game_date, championship_id) VALUES
    (1, 'Clank House - Game 01', '2025-01-04 20:30:00', 1),
    (2, 'Tharsis Room - Game 02', '2025-01-11 20:30:00', 1),
    (3, 'Hellas Table - Game 03', '2025-01-18 20:30:00', 1),
    (4, 'Elysium Loft - Game 04', '2025-01-25 20:30:00', 1),
    (5, 'Noctis Corner - Game 05', '2025-02-01 20:30:00', 1),
    (6, 'Clank House - Game 06', '2025-02-08 20:30:00', 1),
    (7, 'Tharsis Room - Game 07', '2025-02-15 20:30:00', 1),
    (8, 'Hellas Table - Game 08', '2025-02-22 20:30:00', 1),
    (9, 'Elysium Loft - Game 09', '2025-03-01 20:30:00', 1),
    (10, 'Noctis Corner - Game 10', '2025-03-08 20:30:00', 1),
    (11, 'Clank House - Game 11', '2025-03-15 20:30:00', 1),
    (12, 'Tharsis Room - Game 12', '2025-03-22 20:30:00', 1),
    (13, 'Hellas Table - Game 13', '2025-03-29 20:30:00', 1),
    (14, 'Elysium Loft - Game 14', '2025-04-05 20:30:00', 1),
    (15, 'Noctis Corner - Game 15', '2025-04-12 20:30:00', 1),
    (16, 'Ares Pub - Game 01', '2025-05-06 20:30:00', 2),
    (17, 'Daedalia Hall - Game 02', '2025-05-13 20:30:00', 2),
    (18, 'Olympus Club - Game 03', '2025-05-20 20:30:00', 2),
    (19, 'Valles Marineris - Game 04', '2025-05-27 20:30:00', 2),
    (20, 'Phobos Den - Game 05', '2025-06-03 20:30:00', 2),
    (21, 'Ares Pub - Game 06', '2025-06-10 20:30:00', 2),
    (22, 'Daedalia Hall - Game 07', '2025-06-17 20:30:00', 2),
    (23, 'Olympus Club - Game 08', '2025-06-24 20:30:00', 2),
    (24, 'Valles Marineris - Game 09', '2025-07-01 20:30:00', 2),
    (25, 'Phobos Den - Game 10', '2025-07-08 20:30:00', 2),
    (26, 'Ares Pub - Game 11', '2025-07-15 20:30:00', 2),
    (27, 'Daedalia Hall - Game 12', '2025-07-22 20:30:00', 2),
    (28, 'Olympus Club - Game 13', '2025-07-29 20:30:00', 2),
    (29, 'Valles Marineris - Game 14', '2025-08-05 20:30:00', 2),
    (30, 'Phobos Den - Game 15', '2025-08-12 20:30:00', 2),
    (31, 'Hellas Hall - Game 01', '2025-09-05 20:30:00', 3),
    (32, 'Elysium Terrace - Game 02', '2025-09-12 20:30:00', 3),
    (33, 'Vastitas Club - Game 03', '2025-09-19 20:30:00', 3),
    (34, 'Amazonis Table - Game 04', '2025-09-26 20:30:00', 3),
    (35, 'Utopia Room - Game 05', '2025-10-03 20:30:00', 3),
    (36, 'Hellas Hall - Game 06', '2025-10-10 20:30:00', 3),
    (37, 'Elysium Terrace - Game 07', '2025-10-17 20:30:00', 3),
    (38, 'Vastitas Club - Game 08', '2025-10-24 20:30:00', 3),
    (39, 'Amazonis Table - Game 09', '2025-10-31 20:30:00', 3),
    (40, 'Utopia Room - Game 10', '2025-11-07 20:30:00', 3),
    (41, 'Hellas Hall - Game 11', '2025-11-14 20:30:00', 3),
    (42, 'Elysium Terrace - Game 12', '2025-11-21 20:30:00', 3),
    (43, 'Vastitas Club - Game 13', '2025-11-28 20:30:00', 3),
    (44, 'Amazonis Table - Game 14', '2025-12-05 20:30:00', 3),
    (45, 'Utopia Room - Game 15', '2025-12-12 20:30:00', 3);

INSERT INTO points (
    id, terraforming_rating, greenery, city, milestones, awards, cards,
    other_categories, corporation, first_prelude, second_prelude, game, player_id
) VALUES
    (1, 27, 7, 6, 0, 0, 31, '{"Heat":3,"Colonies":2}', 'Polyphemos', 'METAL_RICH_ASTEROID', 'RESEARCH_NETWORK', 1, 1),
    (2, 30, 9, 7, 5, 0, 36, '{}', 'Thorgate', 'BIOLAB', 'SUPPLY_DROP', 1, 2),
    (3, 33, 11, 8, 0, 0, 41, '{}', 'Vitor', 'DONATION', 'ALLIED_BANKS', 1, 3),
    (4, 36, 3, 9, 0, 5, 46, '{"Heat":2,"Venus":2}', 'Aphrodite', 'RESEARCH_NETWORK', 'ACQUIRED_SPACE_AGENCY', 1, 4),
    (5, 21, 5, 10, 0, 0, 20, '{"Colonies":2}', 'StormCraft Incorporated', 'ALLIED_BANKS', 'DOME_FARMING', 1, 5),
    (6, 29, 8, 8, 5, 5, 35, '{}', 'Mining Guild', 'GREAT_AQUIFER', 'ALLIED_BANKS', 2, 1),
    (7, 32, 10, 9, 0, 0, 40, '{}', 'Point Luna', 'EXCENTRIC_SPONSOR', 'ACQUIRED_SPACE_AGENCY', 2, 2),
    (8, 35, 12, 10, 0, 0, 45, '{"Heat":2,"Venus":2}', 'Venera Institute', 'MOHOLE', 'DOME_FARMING', 2, 3),
    (9, 38, 4, 2, 0, 0, 19, '{"Colonies":1}', 'Poseidon', 'SUPPLY_DROP', 'ECOLOGY_EXPERTS', 2, 4),
    (10, 23, 6, 3, 5, 0, 24, '{}', 'Mining Guild', 'ACQUIRED_SPACE_AGENCY', 'VENUS_CONTRACT', 2, 5),
    (11, 31, 9, 10, 0, 0, 39, '{}', 'Valley Trust', 'BIOLAB', 'DOME_FARMING', 3, 1),
    (12, 34, 11, 2, 0, 0, 44, '{"Heat":2,"Venus":2}', 'Morning Star Inc.', 'DONATION', 'ECOLOGY_EXPERTS', 3, 2),
    (13, 37, 3, 3, 0, 5, 49, '{"Colonies":2}', 'Aridor', 'RESEARCH_NETWORK', 'VENUS_CONTRACT', 3, 3),
    (14, 22, 5, 4, 5, 0, 23, '{}', 'Inventrix', 'ALLIED_BANKS', 'COLONY_TRADE_HUB', 3, 4),
    (15, 25, 7, 5, 0, 0, 28, '{"Heat":1}', 'Vitor', 'DOME_FARMING', 'MINING_OPERATION', 3, 5),
    (16, 33, 10, 3, 0, 0, 43, '{"Heat":2,"Venus":2}', 'Manutech', 'EXCENTRIC_SPONSOR', 'VENUS_CONTRACT', 4, 1),
    (17, 36, 12, 4, 0, 0, 48, '{"Colonies":1}', 'Polyphemos', 'MOHOLE', 'COLONY_TRADE_HUB', 4, 2),
    (18, 21, 4, 5, 5, 0, 22, '{}', 'Credicor', 'SUPPLY_DROP', 'MINING_OPERATION', 4, 3),
    (19, 24, 6, 6, 0, 0, 27, '{"Heat":1}', 'Point Luna', 'ACQUIRED_SPACE_AGENCY', 'NITROGEN_SHIPMENT', 4, 4),
    (20, 27, 8, 7, 0, 5, 32, '{"Venus":6}', 'Aphrodite', 'ECOLOGY_EXPERTS', 'POLAR_INDUSTRIES', 4, 5),
    (21, 35, 11, 5, 0, 0, 47, '{"Colonies":2}', 'Arklight', 'DONATION', 'MINING_OPERATION', 5, 1),
    (22, 38, 3, 6, 5, 5, 21, '{}', 'Tharsis Republic', 'RESEARCH_NETWORK', 'NITROGEN_SHIPMENT', 5, 2),
    (23, 23, 5, 7, 0, 0, 26, '{"Heat":1}', 'Valley Trust', 'ALLIED_BANKS', 'POLAR_INDUSTRIES', 5, 3),
    (24, 26, 7, 8, 0, 0, 31, '{"Venus":6}', 'Venera Institute', 'DOME_FARMING', 'APPLIED_SCIENCE', 5, 4),
    (25, 29, 9, 9, 0, 0, 36, '{"Colonies":2}', 'Poseidon', 'VENUS_CONTRACT', 'BUSINESS_EMPIRE', 5, 5),
    (26, 37, 12, 7, 5, 0, 20, '{}', 'Helion', 'MOHOLE', 'POLAR_INDUSTRIES', 6, 1),
    (27, 22, 4, 8, 0, 0, 25, '{"Heat":1}', 'Nirgal Enterprises', 'SUPPLY_DROP', 'APPLIED_SCIENCE', 6, 2),
    (28, 25, 6, 9, 0, 0, 30, '{"Venus":6}', 'Morning Star Inc.', 'ACQUIRED_SPACE_AGENCY', 'BUSINESS_EMPIRE', 6, 3),
    (29, 28, 8, 10, 0, 5, 35, '{"Colonies":1}', 'Aridor', 'ECOLOGY_EXPERTS', 'ORBITAL_CONSTRUCTION_YARD', 6, 4),
    (30, 31, 10, 2, 5, 0, 40, '{"Heat":4}', 'Helion', 'COLONY_TRADE_HUB', 'SMELTING_PLANT', 6, 5),
    (31, 21, 3, 9, 0, 5, 24, '{"Heat":1,"Events":3}', 'Cheung Shing Mars', 'RESEARCH_NETWORK', 'BUSINESS_EMPIRE', 7, 1),
    (32, 24, 5, 10, 0, 0, 29, '{"Venus":6}', 'Manutech', 'ALLIED_BANKS', 'ORBITAL_CONSTRUCTION_YARD', 7, 2),
    (33, 27, 7, 2, 0, 0, 34, '{"Colonies":2}', 'Polyphemos', 'DOME_FARMING', 'SMELTING_PLANT', 7, 3),
    (34, 30, 9, 3, 5, 0, 39, '{"Heat":4}', 'Ecoline', 'VENUS_CONTRACT', 'SELF_SUFFICIENT_SETTLEMENT', 7, 4),
    (35, 33, 11, 4, 0, 0, 44, '{}', 'Valley Trust', 'MINING_OPERATION', 'POWER_GENERATION', 7, 5),
    (36, 23, 4, 2, 0, 0, 28, '{"Venus":6}', 'Celestic', 'SUPPLY_DROP', 'SMELTING_PLANT', 8, 1),
    (37, 26, 6, 3, 0, 0, 33, '{"Colonies":1}', 'Arklight', 'ACQUIRED_SPACE_AGENCY', 'SELF_SUFFICIENT_SETTLEMENT', 8, 2),
    (38, 29, 8, 4, 5, 5, 38, '{"Heat":4}', 'Saturn Systems', 'ECOLOGY_EXPERTS', 'POWER_GENERATION', 8, 3),
    (39, 32, 10, 5, 0, 0, 43, '{}', 'Nirgal Enterprises', 'COLONY_TRADE_HUB', 'EARLY_SETTLEMENT', 8, 4),
    (40, 35, 12, 6, 0, 0, 48, '{"Venus":5}', 'Venera Institute', 'NITROGEN_SHIPMENT', 'MARTIAN_INDUSTRIES', 8, 5),
    (41, 25, 5, 4, 0, 0, 32, '{"Colonies":2}', 'StormCraft Incorporated', 'ALLIED_BANKS', 'POWER_GENERATION', 9, 1),
    (42, 28, 7, 5, 5, 0, 37, '{"Heat":4}', 'Thorgate', 'DOME_FARMING', 'EARLY_SETTLEMENT', 9, 2),
    (43, 31, 9, 6, 0, 0, 42, '{}', 'Cheung Shing Mars', 'VENUS_CONTRACT', 'MARTIAN_INDUSTRIES', 9, 3),
    (44, 34, 11, 7, 0, 0, 47, '{"Venus":5}', 'Morning Star Inc.', 'MINING_OPERATION', 'GALILEAN_MINING', 9, 4),
    (45, 37, 3, 8, 0, 5, 21, '{"Heat":3,"Colonies":2}', 'Aridor', 'POLAR_INDUSTRIES', 'METAL_RICH_ASTEROID', 9, 5),
    (46, 27, 6, 6, 5, 0, 36, '{"Heat":4}', 'Mining Guild', 'ACQUIRED_SPACE_AGENCY', 'MARTIAN_INDUSTRIES', 10, 1),
    (47, 30, 8, 7, 0, 5, 41, '{}', 'Robinson Industries', 'ECOLOGY_EXPERTS', 'GALILEAN_MINING', 10, 2),
    (48, 33, 10, 8, 0, 0, 46, '{"Venus":5}', 'Manutech', 'COLONY_TRADE_HUB', 'METAL_RICH_ASTEROID', 10, 3),
    (49, 36, 12, 9, 0, 0, 20, '{"Heat":3,"Colonies":1}', 'Polyphemos', 'NITROGEN_SHIPMENT', 'GREAT_AQUIFER', 10, 4),
    (50, 21, 4, 10, 5, 0, 25, '{}', 'Mining Guild', 'APPLIED_SCIENCE', 'BIOLAB', 10, 5),
    (51, 29, 7, 8, 0, 0, 40, '{}', 'Vitor', 'DOME_FARMING', 'METAL_RICH_ASTEROID', 11, 1),
    (52, 32, 9, 9, 0, 0, 45, '{"Venus":5}', 'Celestic', 'VENUS_CONTRACT', 'GREAT_AQUIFER', 11, 2),
    (53, 35, 11, 10, 0, 0, 19, '{"Heat":3,"Colonies":2}', 'Arklight', 'MINING_OPERATION', 'BIOLAB', 11, 3),
    (54, 38, 3, 2, 5, 5, 24, '{}', 'Inventrix', 'POLAR_INDUSTRIES', 'EXCENTRIC_SPONSOR', 11, 4),
    (55, 23, 5, 3, 0, 0, 29, '{}', 'Cheung Shing Mars', 'BUSINESS_EMPIRE', 'DONATION', 11, 5),
    (56, 31, 8, 10, 0, 5, 44, '{"Venus":5}', 'Aphrodite', 'ECOLOGY_EXPERTS', 'BIOLAB', 12, 1),
    (57, 34, 10, 2, 0, 0, 49, '{"Heat":3,"Colonies":1}', 'StormCraft Incorporated', 'COLONY_TRADE_HUB', 'EXCENTRIC_SPONSOR', 12, 2),
    (58, 37, 12, 3, 5, 0, 23, '{}', 'Credicor', 'NITROGEN_SHIPMENT', 'DONATION', 12, 3),
    (59, 22, 4, 4, 0, 0, 28, '{}', 'Robinson Industries', 'APPLIED_SCIENCE', 'MOHOLE', 12, 4),
    (60, 25, 6, 5, 0, 0, 33, '{"Heat":2,"Venus":4}', 'Morning Star Inc.', 'ORBITAL_CONSTRUCTION_YARD', 'RESEARCH_NETWORK', 12, 5),
    (61, 33, 9, 3, 0, 0, 48, '{"Heat":3,"Colonies":2}', 'Poseidon', 'VENUS_CONTRACT', 'DONATION', 13, 1),
    (62, 36, 11, 4, 5, 0, 22, '{}', 'Tharsis Republic', 'MINING_OPERATION', 'MOHOLE', 13, 2),
    (63, 21, 3, 5, 0, 5, 27, '{}', 'Vitor', 'POLAR_INDUSTRIES', 'RESEARCH_NETWORK', 13, 3),
    (64, 24, 5, 6, 0, 0, 32, '{"Heat":2,"Venus":4}', 'Manutech', 'BUSINESS_EMPIRE', 'SUPPLY_DROP', 13, 4),
    (65, 27, 7, 7, 0, 0, 37, '{"Colonies":2}', 'Polyphemos', 'SMELTING_PLANT', 'ALLIED_BANKS', 13, 5),
    (66, 35, 10, 5, 5, 0, 21, '{"Events":3}', 'Helion', 'COLONY_TRADE_HUB', 'RESEARCH_NETWORK', 14, 1),
    (67, 38, 12, 6, 0, 0, 26, '{}', 'Point Luna', 'NITROGEN_SHIPMENT', 'SUPPLY_DROP', 14, 2),
    (68, 23, 4, 7, 0, 0, 31, '{"Heat":2,"Venus":4}', 'Celestic', 'APPLIED_SCIENCE', 'ALLIED_BANKS', 14, 3),
    (69, 26, 6, 8, 0, 0, 36, '{"Colonies":1}', 'Arklight', 'ORBITAL_CONSTRUCTION_YARD', 'ACQUIRED_SPACE_AGENCY', 14, 4),
    (70, 29, 8, 9, 5, 5, 41, '{}', 'Helion', 'SELF_SUFFICIENT_SETTLEMENT', 'DOME_FARMING', 14, 5),
    (71, 37, 11, 7, 0, 0, 25, '{}', 'Valley Trust', 'MINING_OPERATION', 'ALLIED_BANKS', 15, 1),
    (72, 22, 3, 8, 0, 5, 30, '{"Heat":2,"Venus":4}', 'Aphrodite', 'POLAR_INDUSTRIES', 'ACQUIRED_SPACE_AGENCY', 15, 2),
    (73, 25, 5, 9, 0, 0, 35, '{"Colonies":2}', 'StormCraft Incorporated', 'BUSINESS_EMPIRE', 'DOME_FARMING', 15, 3),
    (74, 28, 7, 10, 5, 0, 40, '{}', 'Ecoline', 'SMELTING_PLANT', 'ECOLOGY_EXPERTS', 15, 4),
    (75, 31, 9, 2, 0, 0, 45, '{"Heat":1}', 'Vitor', 'POWER_GENERATION', 'VENUS_CONTRACT', 15, 5),
    (76, 28, 8, 7, 5, 5, 34, '{}', 'Mining Guild', 'GREAT_AQUIFER', 'SUPPLY_DROP', 16, 1),
    (77, 31, 10, 8, 0, 0, 39, '{}', 'Point Luna', 'EXCENTRIC_SPONSOR', 'ALLIED_BANKS', 16, 6),
    (78, 34, 12, 9, 0, 0, 44, '{"Heat":1,"Venus":6}', 'Venera Institute', 'MOHOLE', 'ACQUIRED_SPACE_AGENCY', 16, 7),
    (79, 37, 4, 10, 0, 0, 49, '{"Colonies":1}', 'Poseidon', 'SUPPLY_DROP', 'DOME_FARMING', 16, 8),
    (80, 30, 9, 9, 0, 0, 38, '{}', 'Valley Trust', 'BIOLAB', 'ACQUIRED_SPACE_AGENCY', 17, 1),
    (81, 33, 11, 10, 0, 0, 43, '{"Heat":1,"Venus":6}', 'Morning Star Inc.', 'DONATION', 'DOME_FARMING', 17, 6),
    (82, 36, 3, 2, 0, 5, 48, '{"Colonies":3}', 'Aridor', 'RESEARCH_NETWORK', 'ECOLOGY_EXPERTS', 17, 7),
    (83, 21, 5, 3, 5, 0, 22, '{}', 'Inventrix', 'ALLIED_BANKS', 'VENUS_CONTRACT', 17, 8),
    (84, 32, 10, 2, 0, 0, 42, '{"Heat":1,"Venus":6}', 'Manutech', 'EXCENTRIC_SPONSOR', 'ECOLOGY_EXPERTS', 18, 1),
    (85, 35, 12, 3, 0, 0, 47, '{"Colonies":3}', 'Polyphemos', 'MOHOLE', 'VENUS_CONTRACT', 18, 6),
    (86, 38, 4, 4, 5, 0, 21, '{}', 'Credicor', 'SUPPLY_DROP', 'COLONY_TRADE_HUB', 18, 7),
    (87, 23, 6, 5, 0, 0, 26, '{"Heat":4}', 'Point Luna', 'ACQUIRED_SPACE_AGENCY', 'MINING_OPERATION', 18, 8),
    (88, 34, 11, 4, 0, 0, 46, '{"Colonies":1}', 'Arklight', 'DONATION', 'COLONY_TRADE_HUB', 19, 1),
    (89, 37, 3, 5, 5, 5, 20, '{}', 'Tharsis Republic', 'RESEARCH_NETWORK', 'MINING_OPERATION', 19, 6),
    (90, 22, 5, 6, 0, 0, 25, '{"Heat":4}', 'Valley Trust', 'ALLIED_BANKS', 'NITROGEN_SHIPMENT', 19, 7),
    (91, 25, 7, 7, 0, 0, 30, '{"Venus":5}', 'Venera Institute', 'DOME_FARMING', 'POLAR_INDUSTRIES', 19, 8),
    (92, 36, 12, 6, 5, 0, 19, '{}', 'Helion', 'MOHOLE', 'NITROGEN_SHIPMENT', 20, 1),
    (93, 21, 4, 7, 0, 0, 24, '{"Heat":4}', 'Nirgal Enterprises', 'SUPPLY_DROP', 'POLAR_INDUSTRIES', 20, 6),
    (94, 24, 6, 8, 0, 0, 29, '{"Venus":5}', 'Morning Star Inc.', 'ACQUIRED_SPACE_AGENCY', 'APPLIED_SCIENCE', 20, 7),
    (95, 27, 8, 9, 0, 5, 34, '{"Colonies":1}', 'Aridor', 'ECOLOGY_EXPERTS', 'BUSINESS_EMPIRE', 20, 8),
    (96, 38, 3, 8, 0, 5, 23, '{"Heat":4}', 'Cheung Shing Mars', 'RESEARCH_NETWORK', 'APPLIED_SCIENCE', 21, 1),
    (97, 23, 5, 9, 0, 0, 28, '{"Venus":5}', 'Manutech', 'ALLIED_BANKS', 'BUSINESS_EMPIRE', 21, 6),
    (98, 26, 7, 10, 0, 0, 33, '{"Colonies":3}', 'Polyphemos', 'DOME_FARMING', 'ORBITAL_CONSTRUCTION_YARD', 21, 7),
    (99, 29, 9, 2, 5, 0, 38, '{"Heat":3}', 'Ecoline', 'VENUS_CONTRACT', 'SMELTING_PLANT', 21, 8),
    (100, 22, 4, 10, 0, 0, 27, '{"Venus":5,"Events":3}', 'Celestic', 'SUPPLY_DROP', 'ORBITAL_CONSTRUCTION_YARD', 22, 1),
    (101, 25, 6, 2, 0, 0, 32, '{"Colonies":3}', 'Arklight', 'ACQUIRED_SPACE_AGENCY', 'SMELTING_PLANT', 22, 6),
    (102, 28, 8, 3, 5, 5, 37, '{"Heat":3}', 'Saturn Systems', 'ECOLOGY_EXPERTS', 'SELF_SUFFICIENT_SETTLEMENT', 22, 7),
    (103, 31, 10, 4, 0, 0, 42, '{}', 'Nirgal Enterprises', 'COLONY_TRADE_HUB', 'POWER_GENERATION', 22, 8),
    (104, 24, 5, 3, 0, 0, 31, '{"Colonies":1}', 'StormCraft Incorporated', 'ALLIED_BANKS', 'SELF_SUFFICIENT_SETTLEMENT', 23, 1),
    (105, 27, 7, 4, 5, 0, 36, '{"Heat":3}', 'Thorgate', 'DOME_FARMING', 'POWER_GENERATION', 23, 6),
    (106, 30, 9, 5, 0, 0, 41, '{}', 'Cheung Shing Mars', 'VENUS_CONTRACT', 'EARLY_SETTLEMENT', 23, 7),
    (107, 33, 11, 6, 0, 0, 46, '{"Venus":4}', 'Morning Star Inc.', 'MINING_OPERATION', 'MARTIAN_INDUSTRIES', 23, 8),
    (108, 26, 6, 5, 5, 0, 35, '{"Heat":3}', 'Mining Guild', 'ACQUIRED_SPACE_AGENCY', 'EARLY_SETTLEMENT', 24, 1),
    (109, 29, 8, 6, 0, 5, 40, '{}', 'Robinson Industries', 'ECOLOGY_EXPERTS', 'MARTIAN_INDUSTRIES', 24, 6),
    (110, 32, 10, 7, 0, 0, 45, '{"Venus":4}', 'Manutech', 'COLONY_TRADE_HUB', 'GALILEAN_MINING', 24, 7),
    (111, 35, 12, 8, 0, 0, 19, '{"Heat":2,"Colonies":1}', 'Polyphemos', 'NITROGEN_SHIPMENT', 'METAL_RICH_ASTEROID', 24, 8),
    (112, 28, 7, 7, 0, 0, 39, '{}', 'Vitor', 'DOME_FARMING', 'GALILEAN_MINING', 25, 1),
    (113, 31, 9, 8, 0, 0, 44, '{"Venus":4}', 'Celestic', 'VENUS_CONTRACT', 'METAL_RICH_ASTEROID', 25, 6),
    (114, 34, 11, 9, 0, 0, 49, '{"Heat":2,"Colonies":3}', 'Arklight', 'MINING_OPERATION', 'GREAT_AQUIFER', 25, 7),
    (115, 37, 3, 10, 5, 5, 23, '{}', 'Inventrix', 'POLAR_INDUSTRIES', 'BIOLAB', 25, 8),
    (116, 30, 8, 9, 0, 5, 43, '{"Venus":4}', 'Aphrodite', 'ECOLOGY_EXPERTS', 'GREAT_AQUIFER', 26, 1),
    (117, 33, 10, 10, 0, 0, 48, '{"Heat":2,"Colonies":3}', 'StormCraft Incorporated', 'COLONY_TRADE_HUB', 'BIOLAB', 26, 6),
    (118, 36, 12, 2, 5, 0, 22, '{}', 'Credicor', 'NITROGEN_SHIPMENT', 'EXCENTRIC_SPONSOR', 26, 7),
    (119, 21, 4, 3, 0, 0, 27, '{}', 'Robinson Industries', 'APPLIED_SCIENCE', 'DONATION', 26, 8),
    (120, 32, 9, 2, 0, 0, 47, '{"Heat":2,"Colonies":1}', 'Poseidon', 'VENUS_CONTRACT', 'EXCENTRIC_SPONSOR', 27, 1),
    (121, 35, 11, 3, 5, 0, 21, '{}', 'Tharsis Republic', 'MINING_OPERATION', 'DONATION', 27, 6),
    (122, 38, 3, 4, 0, 5, 26, '{}', 'Vitor', 'POLAR_INDUSTRIES', 'MOHOLE', 27, 7),
    (123, 23, 5, 5, 0, 0, 31, '{"Heat":1,"Venus":3}', 'Manutech', 'BUSINESS_EMPIRE', 'RESEARCH_NETWORK', 27, 8),
    (124, 34, 10, 4, 5, 0, 20, '{}', 'Helion', 'COLONY_TRADE_HUB', 'MOHOLE', 28, 1),
    (125, 37, 12, 5, 0, 0, 25, '{}', 'Point Luna', 'NITROGEN_SHIPMENT', 'RESEARCH_NETWORK', 28, 6),
    (126, 22, 4, 6, 0, 0, 30, '{"Heat":1,"Venus":3}', 'Celestic', 'APPLIED_SCIENCE', 'SUPPLY_DROP', 28, 7),
    (127, 25, 6, 7, 0, 0, 35, '{"Colonies":1}', 'Arklight', 'ORBITAL_CONSTRUCTION_YARD', 'ALLIED_BANKS', 28, 8),
    (128, 36, 11, 6, 0, 0, 24, '{"Events":3}', 'Valley Trust', 'MINING_OPERATION', 'SUPPLY_DROP', 29, 1),
    (129, 21, 3, 7, 0, 5, 29, '{"Heat":1,"Venus":3}', 'Aphrodite', 'POLAR_INDUSTRIES', 'ALLIED_BANKS', 29, 6),
    (130, 24, 5, 8, 0, 0, 34, '{"Colonies":3}', 'StormCraft Incorporated', 'BUSINESS_EMPIRE', 'ACQUIRED_SPACE_AGENCY', 29, 7),
    (131, 27, 7, 9, 5, 0, 39, '{}', 'Ecoline', 'SMELTING_PLANT', 'DOME_FARMING', 29, 8),
    (132, 38, 12, 8, 0, 0, 28, '{"Heat":1,"Venus":3}', 'Venera Institute', 'NITROGEN_SHIPMENT', 'ACQUIRED_SPACE_AGENCY', 30, 1),
    (133, 23, 4, 9, 0, 0, 33, '{"Colonies":3}', 'Poseidon', 'APPLIED_SCIENCE', 'DOME_FARMING', 30, 6),
    (134, 26, 6, 10, 5, 0, 38, '{}', 'Saturn Systems', 'ORBITAL_CONSTRUCTION_YARD', 'ECOLOGY_EXPERTS', 30, 7),
    (135, 29, 8, 2, 0, 5, 43, '{"Heat":4}', 'Point Luna', 'SELF_SUFFICIENT_SETTLEMENT', 'VENUS_CONTRACT', 30, 8),
    (136, 29, 9, 8, 0, 0, 37, '{}', 'Valley Trust', 'BIOLAB', 'ALLIED_BANKS', 31, 3),
    (137, 32, 11, 9, 0, 0, 42, '{"Heat":4,"Venus":5}', 'Morning Star Inc.', 'DONATION', 'ACQUIRED_SPACE_AGENCY', 31, 5),
    (138, 35, 3, 10, 0, 5, 47, '{"Colonies":4}', 'Aridor', 'RESEARCH_NETWORK', 'DOME_FARMING', 31, 9),
    (139, 31, 10, 10, 0, 0, 41, '{"Heat":4,"Venus":5}', 'Manutech', 'EXCENTRIC_SPONSOR', 'DOME_FARMING', 32, 3),
    (140, 34, 12, 2, 0, 0, 46, '{"Colonies":1}', 'Polyphemos', 'MOHOLE', 'ECOLOGY_EXPERTS', 32, 5),
    (141, 37, 4, 3, 5, 0, 20, '{}', 'Credicor', 'SUPPLY_DROP', 'VENUS_CONTRACT', 32, 9),
    (142, 33, 11, 3, 0, 0, 45, '{"Colonies":4}', 'Arklight', 'DONATION', 'VENUS_CONTRACT', 33, 3),
    (143, 36, 3, 4, 5, 5, 19, '{}', 'Tharsis Republic', 'RESEARCH_NETWORK', 'COLONY_TRADE_HUB', 33, 5),
    (144, 21, 5, 5, 0, 0, 24, '{"Heat":3}', 'Valley Trust', 'ALLIED_BANKS', 'MINING_OPERATION', 33, 9),
    (145, 35, 12, 5, 5, 0, 49, '{}', 'Helion', 'MOHOLE', 'MINING_OPERATION', 34, 3),
    (146, 38, 4, 6, 0, 0, 23, '{"Heat":3}', 'Nirgal Enterprises', 'SUPPLY_DROP', 'NITROGEN_SHIPMENT', 34, 5),
    (147, 23, 6, 7, 0, 0, 28, '{"Venus":4}', 'Morning Star Inc.', 'ACQUIRED_SPACE_AGENCY', 'POLAR_INDUSTRIES', 34, 9),
    (148, 37, 3, 7, 0, 5, 22, '{"Heat":3}', 'Cheung Shing Mars', 'RESEARCH_NETWORK', 'POLAR_INDUSTRIES', 35, 3),
    (149, 22, 5, 8, 0, 0, 27, '{"Venus":4}', 'Manutech', 'ALLIED_BANKS', 'APPLIED_SCIENCE', 35, 5),
    (150, 25, 7, 9, 0, 0, 32, '{"Colonies":4}', 'Polyphemos', 'DOME_FARMING', 'BUSINESS_EMPIRE', 35, 9),
    (151, 21, 4, 9, 0, 0, 26, '{"Venus":4}', 'Celestic', 'SUPPLY_DROP', 'BUSINESS_EMPIRE', 36, 3),
    (152, 24, 6, 10, 0, 0, 31, '{"Colonies":1}', 'Arklight', 'ACQUIRED_SPACE_AGENCY', 'ORBITAL_CONSTRUCTION_YARD', 36, 5),
    (153, 27, 8, 2, 5, 5, 36, '{"Heat":2}', 'Saturn Systems', 'ECOLOGY_EXPERTS', 'SMELTING_PLANT', 36, 9),
    (154, 23, 5, 2, 0, 0, 30, '{"Colonies":4,"Events":3}', 'StormCraft Incorporated', 'ALLIED_BANKS', 'SMELTING_PLANT', 37, 3),
    (155, 26, 7, 3, 5, 0, 35, '{"Heat":2}', 'Thorgate', 'DOME_FARMING', 'SELF_SUFFICIENT_SETTLEMENT', 37, 5),
    (156, 29, 9, 4, 0, 0, 40, '{}', 'Cheung Shing Mars', 'VENUS_CONTRACT', 'POWER_GENERATION', 37, 9),
    (157, 25, 6, 4, 5, 0, 34, '{"Heat":2}', 'Mining Guild', 'ACQUIRED_SPACE_AGENCY', 'POWER_GENERATION', 38, 3),
    (158, 28, 8, 5, 0, 5, 39, '{}', 'Robinson Industries', 'ECOLOGY_EXPERTS', 'EARLY_SETTLEMENT', 38, 5),
    (159, 31, 10, 6, 0, 0, 44, '{"Venus":3}', 'Manutech', 'COLONY_TRADE_HUB', 'MARTIAN_INDUSTRIES', 38, 9),
    (160, 27, 7, 6, 0, 0, 38, '{}', 'Vitor', 'DOME_FARMING', 'MARTIAN_INDUSTRIES', 39, 3),
    (161, 30, 9, 7, 0, 0, 43, '{"Venus":3}', 'Celestic', 'VENUS_CONTRACT', 'GALILEAN_MINING', 39, 5),
    (162, 33, 11, 8, 0, 0, 48, '{"Heat":1,"Colonies":4}', 'Arklight', 'MINING_OPERATION', 'METAL_RICH_ASTEROID', 39, 9),
    (163, 29, 8, 8, 0, 5, 42, '{"Venus":3}', 'Aphrodite', 'ECOLOGY_EXPERTS', 'METAL_RICH_ASTEROID', 40, 3),
    (164, 32, 10, 9, 0, 0, 47, '{"Heat":1,"Colonies":1}', 'StormCraft Incorporated', 'COLONY_TRADE_HUB', 'GREAT_AQUIFER', 40, 5),
    (165, 35, 12, 10, 5, 0, 21, '{}', 'Credicor', 'NITROGEN_SHIPMENT', 'BIOLAB', 40, 9),
    (166, 31, 9, 10, 0, 0, 46, '{"Heat":1,"Colonies":4}', 'Poseidon', 'VENUS_CONTRACT', 'BIOLAB', 41, 3),
    (167, 34, 11, 2, 5, 0, 20, '{}', 'Tharsis Republic', 'MINING_OPERATION', 'EXCENTRIC_SPONSOR', 41, 5),
    (168, 37, 3, 3, 0, 5, 25, '{}', 'Vitor', 'POLAR_INDUSTRIES', 'DONATION', 41, 9),
    (169, 33, 10, 3, 5, 0, 19, '{}', 'Helion', 'COLONY_TRADE_HUB', 'DONATION', 42, 3),
    (170, 36, 12, 4, 0, 0, 24, '{}', 'Point Luna', 'NITROGEN_SHIPMENT', 'MOHOLE', 42, 5),
    (171, 21, 4, 5, 0, 0, 29, '{"Heat":4,"Venus":2}', 'Celestic', 'APPLIED_SCIENCE', 'RESEARCH_NETWORK', 42, 9),
    (172, 35, 11, 5, 0, 0, 23, '{}', 'Valley Trust', 'MINING_OPERATION', 'RESEARCH_NETWORK', 43, 3),
    (173, 38, 3, 6, 0, 5, 28, '{"Heat":4,"Venus":2}', 'Aphrodite', 'POLAR_INDUSTRIES', 'SUPPLY_DROP', 43, 5),
    (174, 23, 5, 7, 0, 0, 33, '{"Colonies":4}', 'StormCraft Incorporated', 'BUSINESS_EMPIRE', 'ALLIED_BANKS', 43, 9),
    (175, 37, 12, 7, 0, 0, 27, '{"Heat":4,"Venus":2,"Events":3}', 'Venera Institute', 'NITROGEN_SHIPMENT', 'ALLIED_BANKS', 44, 3),
    (176, 22, 4, 8, 0, 0, 32, '{"Colonies":1}', 'Poseidon', 'APPLIED_SCIENCE', 'ACQUIRED_SPACE_AGENCY', 44, 5),
    (177, 25, 6, 9, 5, 0, 37, '{}', 'Saturn Systems', 'ORBITAL_CONSTRUCTION_YARD', 'DOME_FARMING', 44, 9),
    (178, 21, 3, 9, 0, 5, 31, '{"Colonies":4}', 'Aridor', 'POLAR_INDUSTRIES', 'DOME_FARMING', 45, 3),
    (179, 24, 5, 10, 5, 0, 36, '{}', 'Thorgate', 'BUSINESS_EMPIRE', 'ECOLOGY_EXPERTS', 45, 5),
    (180, 27, 7, 2, 0, 0, 41, '{"Heat":3}', 'Valley Trust', 'SMELTING_PLANT', 'VENUS_CONTRACT', 45, 9);

INSERT INTO drafting (id, draftings, player_id, championship) VALUES
    (1, '{"1":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"2":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"3":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"4":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"5":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"6":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"7":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"8":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"9":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"10":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"11":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"12":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"13":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"14":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"15":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"}}', 1, 1),
    (2, '{"1":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"2":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"3":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"4":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"5":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"6":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"7":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"8":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"9":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"10":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"11":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"12":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"13":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"14":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"15":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"}}', 2, 1),
    (3, '{"1":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"2":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"3":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"4":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"5":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"6":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"7":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"8":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"9":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"10":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"11":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"12":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"13":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"14":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"15":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"}}', 3, 1),
    (4, '{"1":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"2":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"3":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"4":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"5":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"6":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"7":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"8":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"9":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"10":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"11":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"12":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"13":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"14":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"15":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"}}', 4, 1),
    (5, '{"1":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"2":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"3":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"4":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"5":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"6":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"7":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"8":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"9":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"10":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"11":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"12":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"13":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"14":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"15":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"}}', 5, 1),
    (6, '{"1":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"2":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"3":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"4":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"5":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"6":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"7":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"8":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"9":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"10":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"11":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"12":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"13":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"14":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"15":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"}}', 1, 2),
    (7, '{"1":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"2":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"3":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"4":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"5":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"6":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"7":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"8":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"9":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"10":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"11":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"12":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"13":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"14":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"15":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"}}', 6, 2),
    (8, '{"1":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"2":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"3":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"4":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"5":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"6":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"7":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"8":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"9":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"10":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"11":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"12":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"13":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"14":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"15":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"}}', 7, 2),
    (9, '{"1":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"2":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"3":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"4":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"5":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"6":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"7":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"8":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"9":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"10":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"11":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"12":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"13":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"14":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"15":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"}}', 8, 2),
    (10, '{"1":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"2":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"3":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"4":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"5":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"6":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"7":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"8":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"9":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"10":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"11":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"12":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"13":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"14":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"15":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"}}', 3, 3),
    (11, '{"1":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"2":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"3":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"4":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"5":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"6":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"7":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"8":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"9":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"10":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"11":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"12":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"13":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"14":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"15":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"}}', 5, 3),
    (12, '{"1":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"2":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"3":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"4":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"5":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"6":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"7":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"8":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"9":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"10":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"11":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"},"12":{"firstExpansion":"Venus Next","secondExpansion":"Corporate Era","chosenExpansion":"Venus Next"},"13":{"firstExpansion":"Colonies","secondExpansion":"Prelude","chosenExpansion":"Colonies"},"14":{"firstExpansion":"Corporate Era","secondExpansion":"Prelude","chosenExpansion":"Corporate Era"},"15":{"firstExpansion":"Prelude","secondExpansion":"Corporate Era","chosenExpansion":"Prelude"}}', 9, 3);

ALTER SEQUENCE championship_seq RESTART WITH 1000;
ALTER SEQUENCE game_seq RESTART WITH 1000;
ALTER SEQUENCE player_seq RESTART WITH 1000;
ALTER SEQUENCE points_seq RESTART WITH 1000;
ALTER SEQUENCE drafting_seq RESTART WITH 1000;
ALTER SEQUENCE hibernate_sequence RESTART WITH 1000;

-- Seed summary: 3 championships, 45 games, 180 points rows, 12 drafting rows.
